name: Buytime
description: Give you a star!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.4

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.0.2
  google_maps_flutter: ^2.0.3
#  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^1.0.5
  firebase_storage: ^8.1.0
  firebase_storage_web: ^1.0.3
  firebase_core: ^1.2.0
  firebase_analytics: ^8.0.0
  firebase_auth: ^1.1.0
  firebase_dynamic_links: ^2.0.0
  firebase_messaging: ^10.0.0
  email_validator: ^2.0.1
  progress_dialog: ^1.2.4
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter_redux: ^0.8.2
  redux_epics: 0.15.0
  rxdart: ^0.26.0
  permission_handler: ^7.1.0
  permission_handler_platform_interface: ^3.1.3
  image_picker: ^0.7.4
  image_picker_for_web: ^2.0.0
  device_info: ^2.0.0
  device_info_platform_interface: ^2.0.1
  share: ^2.0.1
  uuid: ^3.0.4
  crop: ^0.5.0
  mime: ^1.0.0
  flutter_svg: ^0.21.0+1
  badges: ^1.2.0
  url_launcher: ^6.0.3
  stripe_payment: ^1.1.0
  stripe_sdk: ^5.0.0-nullsafety.0
  credit_card_input_form: ^2.3.0
  http: ^0.13.0
#  modal_progress_hud: ^0.1.3
  flutter_redux_navigation: ^0.7.0
  video_player: ^2.1.1
  flutter_pdfview: ^1.1.0
  path_provider: ^2.0.1
  crypto: ^3.0.1
  sign_in_with_apple: ^3.0.0
  animations: ^2.0.0
  flutter_spinkit: ^5.0.0
  image_cropper: ^1.4.0
  intl: ^0.17.0-nullsafety.2
  qr_flutter: ^4.0.0
  cached_network_image: ^3.0.0
  flutter_secure_storage: ^4.1.0
  flutter_screenutil: ^5.0.0
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
#  logger_flutter: ^0.7.1
#  logger: ^1.0.0
  add_2_calendar: ^2.0.2
  app_tracking_transparency: ^2.0.0+1
  local_auth: ^1.1.4
  image: ^3.0.2
  credit_card_type_detector: ^2.0.0-nullsafety.0
  flutter_picker: ^2.0.1
  carousel_pro: ^1.0.0
  flutter_icons: ^1.1.0
  map_launcher: ^2.0.0
  another_flushbar: ^1.10.22
  #flutter_treeview: ^0.9.0+1
  emojis: ^0.9.3
  google_place: ^0.4.0
  scrollable_positioned_list: ^0.1.8
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  location: ^4.1.1
  plugin_platform_interface: ^2.0.0


dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.10.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/golfCourt.png
    - assets/img/nobookings.png
    - assets/img/iceresort.png
    - assets/img/hermitage.png
    - assets/img/placeholder.png
    - assets/img/image_placeholder.png
    - assets/img/image_placeholder_square.png
    - assets/img/image_placeholder_square_upload.png
    - assets/img/beach_girl.png
    - assets/img/booking_code.png
    - assets/img/img_buytime.png
    - assets/img/apple_logo.png
    - assets/img/google_logo.png
    - assets/img/facebook_logo.png
    - assets/img/back_button.png
    - assets/img/back_blue.png
    - assets/img/qr_code.png
    - assets/img/pointer.png
    - assets/img/3archi.jpg
    - assets/img/approdo.jpeg
    - assets/img/rifrullo.jpg
    - assets/img/zucchetta.jpeg
    - assets/img/mach1.jpg
    - assets/img/star_off.png
    - assets/img/star_on.png
    - assets/img/pin_off.png
    - assets/img/pin_on.png
    - assets/img/search.png
    - assets/img/user.png
    - assets/img/euro_off.png
    - assets/img/euro_on.png
    - assets/img/hotel.png
    - assets/img/food.png
    - assets/img/back.png
    - assets/img/magic.png
    - assets/img/white_plus.png
    - assets/img/blue_plus.png
    - assets/img/group.png
    - assets/img/fake_user.png
    - assets/img/lion_logo.png
    - assets/img/lion_photo.png
    - assets/img/upload.png
    - assets/img/brand/logo.png
    - assets/img/brand/logo_appbar.svg
    - assets/img/brand/logo_appbar.png
    - assets/img/brand/logo_b.png
    - assets/img/image_placeholder.png
    - assets/img/aboutus.png
    - assets/img/apple_pay.jpg
    - assets/img/google_pay.jpg
    - assets/img/visa.jpg
    - assets/img/mastercard.png
    - assets/icon.jpeg
    - assets/icon.png
    - assets/video/
    - assets/documents/
    - assets/img/spinner/
    - assets/img/cc/
    - assets/json/
    - assets/img/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Thin.ttf
  - family: MaterialDesignIcons
    fonts:
      - asset: fonts/MaterialDesignIcons.ttf
  - family: BuytimeIcons
    fonts:
      - asset: fonts/Buytime.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages