name: Buytime
description: Give you a star!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  email_validator: ^1.0.6
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  progress_dialog: ^1.2.4
  firebase_auth: ^0.20.0+1
  nfc_in_flutter: ^2.0.5
  shared_preferences: ^0.5.12+4
  cupertino_icons: ^1.0.2
  flutter_redux: ^0.7.0
  redux_epics: 0.14.0
  rxdart: ^0.24.0
  permission_handler: ^5.0.1+1
#  permission_handler:
#    git:
#      url: https://github.com/romme86/flutter-permission-handler/permission_handler
  image_picker: ^0.6.7+21
  image_picker_for_web: ^0.1.0+2
  firebase_dynamic_links: ^0.7.0+1
  firebase_messaging: ^8.0.0-dev.14
  device_info: ^1.0.0
#  stripe_sdk: ^4.0.2
  stripe_sdk:
    git:
      url: https://github.com/romme86/stripe-sdk
  share: ^0.6.5+4
  uuid: ^2.2.2
  crop: any
  mime: ^0.9.7
  flutter_svg: ^0.19.3
  badges: ^1.1.6
  url_launcher: ^5.7.2
  stripe_payment: ^1.0.9
  http: ^0.12.2
  modal_progress_hud: ^0.1.3
  flutter_redux_navigation: ^0.6.0
  video_player: ^1.0.1
  flutter_pdfview: ^1.0.4
  path_provider: ^1.6.27
  crypto: ^2.1.5
  sign_in_with_apple: ^3.0.0
  animations: ^1.1.2
  flutter_spinkit: ^4.1.2+1
  image_cropper: ^1.3.1
  intl: ^0.16.1
  qr_flutter: ^3.2.0
  cached_network_image: ^2.5.0
  flutter_secure_storage: ^4.1.0
  flutter_screenutil: ^4.0.3+2
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  logger_flutter: ^0.7.1
  logger: ^0.7.0
  add_2_calendar: ^1.4.0
  local_auth: ^0.6.3+4
  image: ^2.1.18
  credit_card_type_detector: ^1.1.0
  flutter_picker: ^2.0.1
  carousel_pro: ^1.0.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.10.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/golfCourt.png
    - assets/img/nobookings.png
    - assets/img/iceresort.png
    - assets/img/hermitage.png
    - assets/img/placeholder.png
    - assets/img/image_placeholder.png
    - assets/img/image_placeholder_square.png
    - assets/img/image_placeholder_square_upload.png
    - assets/img/beach_girl.png
    - assets/img/booking_code.png
    - assets/img/img_buytime.png
    - assets/img/apple_logo.png
    - assets/img/google_logo.png
    - assets/img/facebook_logo.png
    - assets/img/back_button.png
    - assets/img/back_blue.png
    - assets/img/qr_code.png
    - assets/img/hand_nfc.png
    - assets/img/nfc.png
    - assets/img/pointer.png
    - assets/img/3archi.jpg
    - assets/img/approdo.jpeg
    - assets/img/rifrullo.jpg
    - assets/img/zucchetta.jpeg
    - assets/img/mach1.jpg
    - assets/img/star_off.png
    - assets/img/star_on.png
    - assets/img/pin_off.png
    - assets/img/pin_on.png
    - assets/img/search.png
    - assets/img/user.png
    - assets/img/euro_off.png
    - assets/img/euro_on.png
    - assets/img/hotel.png
    - assets/img/food.png
    - assets/img/back.png
    - assets/img/magic.png
    - assets/img/white_plus.png
    - assets/img/blue_plus.png
    - assets/img/group.png
    - assets/img/fake_user.png
    - assets/img/lion_logo.png
    - assets/img/lion_photo.png
    - assets/img/upload.png
    - assets/img/brand/logo.png
    - assets/img/brand/logo_appbar.svg
    - assets/img/brand/logo_appbar.png
    - assets/img/brand/logo_b.png
    - assets/img/image_placeholder.png
    - assets/img/aboutus.png
    - assets/img/apple_pay.jpg
    - assets/img/google_pay.jpg
    - assets/img/visa.jpg
    - assets/img/mastercard.png
    - assets/icon.jpeg
    - assets/icon.png
    - assets/video/
    - assets/documents/tc.pdf
    - assets/documents/tos.pdf
    - assets/img/spinner/
    - assets/img/cc/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Thin.ttf
  - family: MaterialDesignIcons
    fonts:
      - asset: fonts/MaterialDesignIcons.ttf
  - family: BuytimeIcons
    fonts:
      - asset: fonts/Buytime.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages