/// Flutter icons Cart
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cart
///      fonts:
///       - asset: fonts/Cart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CartIcon {
  CartIcon._();

  static const _kFontFam = 'CartIcon';
  static const String _kFontPkg = null;

  static const IconData add_shopping_cart_24px = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
